Repository 15-en1576nd/mastermind-laravel, pull requests merged in 2021-12, with the labels that each got.

#46 refactor: split up blade stuff more
  app/Http/Controllers/GameDatabaseController.php
  app/Http/Controllers/MastermindGameController.php
  app/Http/Controllers/ScoreboardController.php
  app/Http/Controllers/SelectedEmojiController.php
  app/View/Components/playbutton.php
  resources/lang/en/shorts.php
  resources/lang/nl/shorts.php
  resources/views/components/emojipicker.blade.php
  resources/views/components/gameboard.blade.php
  resources/views/components/playbutton.blade.php
  resources/views/components/scoreboard.blade.php
  resources/views/components/socialmediabuttons.blade.php
  resources/views/layouts/app.blade.php
  resources/views/mastermind/game.blade.php
  resources/views/welcome.blade.php
Labels: refactor

#47 feat: initialize breeze
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Controllers/Auth/ConfirmablePasswordController.php
  app/Http/Controllers/Auth/EmailVerificationNotificationController.php
  app/Http/Controllers/Auth/EmailVerificationPromptController.php
  app/Http/Controllers/Auth/NewPasswordController.php
  app/Http/Controllers/Auth/PasswordResetLinkController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/VerifyEmailController.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Providers/RouteServiceProvider.php
  app/View/Components/AppLayout.php
  app/View/Components/GuestLayout.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  public/css/app.css
  public/js/app.js
  resources/css/app.css
  resources/js/app.js
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/reset-password.blade.php
  resources/views/auth/verify-email.blade.php
  resources/views/components/application-logo.blade.php
  resources/views/components/auth-card.blade.php
  resources/views/components/auth-session-status.blade.php
  resources/views/components/auth-validation-errors.blade.php
  resources/views/components/button.blade.php
  resources/views/components/dropdown-link.blade.php
  resources/views/components/dropdown.blade.php
  resources/views/components/input.blade.php
  resources/views/components/label.blade.php
  resources/views/components/nav-link.blade.php
  resources/views/components/responsive-nav-link.blade.php
  resources/views/dashboard.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/auth.php
  routes/web.php
  tailwind.config.js
  tests/Feature/Auth/AuthenticationTest.php
  tests/Feature/Auth/EmailVerificationTest.php
  tests/Feature/Auth/PasswordResetTest.php
  tests/Feature/Auth/RegistrationTest.php
  webpack.mix.js
Labels: enhancement

#49 feat: gamehints
  app/View/Components/gamehints.php
  resources/views/components/gameboard.blade.php
  resources/views/components/gamehints.blade.php
  resources/views/components/playbutton.blade.php
Labels: enhancement, help wanted
